In [1]:
import pandas as pd

In [2]:
cricket=pd.read_html('https://www.espncricinfo.com/rankings/content/page/211271.html')

In [3]:
cricket

[   Pos          Team  Matches  Points  Rating
 0    1         India       26    3097     119
 1    2     Australia       24    2850     119
 2    3       England       36    4103     114
 3    4  South Africa       21    2182     104
 4    5   New Zealand       23    2291     100
 5    6      Pakistan       22    1902      86
 6    7     Sri Lanka       24    2015      84
 7    8   West Indies       25    1906      76
 8    9    Bangladesh       19     873      46
 9   10      Zimbabwe        7     223      32,
     Pos          Team  Matches  Points  Rating
 0     1     Australia       23    2714     118
 1     2      Pakistan       20    2316     116
 2     3         India       33    3807     115
 3     4   New Zealand       27    2806     104
 4     5       England       24    2426     101
 5     6  South Africa       19    1910     101
 6     7    Bangladesh       28    2661      95
 7     8   Afghanistan       16    1404      88
 8     9     Sri Lanka       32    2794      87
 9    10   West Indies       35    2312      66
 10   11      Zimbabwe       30    1641      55
 11   12      Scotland       33    1662      50
 12   13       Ireland       24    1052      44
 13   14   Netherlands       28    1044      37
 14   15         Nepal       40    1396      35
 15   16       Namibia       28     813      29
 16   17           USA       31     808      26
 17   18          Oman       24     525      22
 18   19           UAE       41     617      15
 19   20           PNG       28     106       4,
     Pos          Team  Matches  Points  Rating
 0     1         India       52   13889     267
 1     2       England       39   10117     259
 2     3   New Zealand       46   11794     256
 3     4      Pakistan       50   12719     254
 4     5  South Africa       32    8080     253
 ..  ...           ...      ...     ...     ...
 82   83    Seychelles        7       0       0
 83   84         Samoa        9       0       0
 84   85       Estonia        9       0       0
 85   86      Cameroon       11       0       0
 86   87        Greece        6       0       0

 [87 rows x 5 columns],
     Pos                Team  Matches  Points  Rating
 0     1     Australia Women       21    3603     172
 1     2       England Women       28    3342     119
 2     3  South Africa Women       26    3098     119
 3     4         India Women       27    2820     104
 4     5   New Zealand Women       28    2688      96
 5     6   West Indies Women       29    2743      95
 6     7    Bangladesh Women       14     977      70
 7     8     Sri Lanka Women       12     820      68
 8     9      Thailand Women       13     883      68
 9    10      Pakistan Women       27    1678      62
 10   11       Ireland Women       16     605      38
 11   12   Netherlands Women       11      89       8
 12   13      Zimbabwe Women       11       0       0,
     Pos                Team  Matches  Points  Rating
 0     1     Australia Women       32    9548     298
 1     2       England Women       38   10841     285
 2     3   New Zealand Women       31    8247     266
 3     4         India Women       48   12736     265
 4     5  South Africa Women       27    6831     253
 ..  ...                 ...      ...     ...     ...
 56   57  Phlilippines Women       11       0       0
 57   58        Norway Women        9       0       0
 58   59         Ghana Women        9       0       0
 59   60       Austria Women       21       0       0
 60   61          Peru Women        5       0       0

 [61 rows x 5 columns]]

In [4]:
pd.set_option('display.max_row',None)

In [5]:
cricket

[   Pos          Team  Matches  Points  Rating
 0    1         India       26    3097     119
 1    2     Australia       24    2850     119
 2    3       England       36    4103     114
 3    4  South Africa       21    2182     104
 4    5   New Zealand       23    2291     100
 5    6      Pakistan       22    1902      86
 6    7     Sri Lanka       24    2015      84
 7    8   West Indies       25    1906      76
 8    9    Bangladesh       19     873      46
 9   10      Zimbabwe        7     223      32,
     Pos          Team  Matches  Points  Rating
 0     1     Australia       23    2714     118
 1     2      Pakistan       20    2316     116
 2     3         India       33    3807     115
 3     4   New Zealand       27    2806     104
 4     5       England       24    2426     101
 5     6  South Africa       19    1910     101
 6     7    Bangladesh       28    2661      95
 7     8   Afghanistan       16    1404      88
 8     9     Sri Lanka       32    2794      87
 9    10   West Indies       35    2312      66
 10   11      Zimbabwe       30    1641      55
 11   12      Scotland       33    1662      50
 12   13       Ireland       24    1052      44
 13   14   Netherlands       28    1044      37
 14   15         Nepal       40    1396      35
 15   16       Namibia       28     813      29
 16   17           USA       31     808      26
 17   18          Oman       24     525      22
 18   19           UAE       41     617      15
 19   20           PNG       28     106       4,
     Pos            Team  Matches  Points  Rating
 0     1           India       52   13889     267
 1     2         England       39   10117     259
 2     3     New Zealand       46   11794     256
 3     4        Pakistan       50   12719     254
 4     5    South Africa       32    8080     253
 5     6       Australia       31    7681     248
 6     7     West Indies       34    8086     238
 7     8       Sri Lanka       37    8774     237
 8     9      Bangladesh       39    8656     222
 9    10     Afghanistan       27    5915     219
 10   11        Zimbabwe       36    7087     197
 11   12         Ireland       37    7168     194
 12   13         Namibia       17    3228     190
 13   14        Scotland       12    2195     183
 14   15     Netherlands       19    3445     181
 15   16             UAE       17    3029     178
 16   17           Nepal       14    2491     178
 17   18       Hong Kong       14    2052     147
 18   19          Canada       13    1871     144
 19   20            Oman       13    1823     140
 20   21          Jersey       13    1718     132
 21   22             PNG       12    1581     132
 22   23             USA        9    1183     131
 23   24          Uganda       42    5407     129
 24   25        Malaysia       27    3307     122
 25   26           Qatar        7     832     119
 26   27          Kuwait       14    1648     118
 27   28         Bahrain       27    2848     105
 28   29           Kenya       30    3137     105
 29   30        Tanzania       31    3151     102
 30   31         Germany       25    2424      97
 31   32         Bermuda        9     862      96
 32   33    Saudi Arabia        9     859      95
 33   34           Spain       18    1649      92
 34   35           Italy       12    1094      91
 35   36       Singapore       23    1840      80
 36   37  Cayman Islands        7     521      74
 37   38        Portugal       16    1167      73
 38   39         Denmark       17    1234      73
 39   40         Belgium       18    1237      69
 40   41         Nigeria       15    1026      68
 41   42         Vanuatu        9     607      67
 42   43        Guernsey       13     876      67
 43   44     Isle of Man       15     949      63
 44   45         Austria       24    1465      61
 45   46          Norway       15     852      57
 46   47        Botswana       24    1300      54
 47   48         Finland       18     953      53
 48   49          France       10     515      52
 49   50         Romania       18     884      49
 50   51          Malawi       14     682      49
 51   52  Czech Republic       24    1101      46
 52   53          Sweden       18     759      42
 53   54    Cook Islands        6     245      41
 54   55       Indonesia       10     372      37
 55   56      Mozambique       21     759      36
 56   57    Sierra Leone       12     421      35
 57   58     Switzerland       11     376      34
 58   59          Bhutan        7     239      34
 59   60           Malta       33    1120      34
 60   61           Japan        7     236      34
 61   62           Ghana       16     516      32
 62   63          Rwanda       38    1171      31
 63   64     Philippines        5     154      31
 64   65       Argentina        9     274      30
 65   66            Fiji       10     304      30
 66   67      Luxembourg       22     660      30
 67   68          Cyprus        8     206      26
 68   69         Bahamas       10     241      24
 69   70          Panama        7     160      23
 70   71          Belize        3      66      22
 71   72          Serbia       17     351      21
 72   73         Hungary       17     264      16
 73   74        Bulgaria       30     289      10
 74   75         Lesotho        9      82       9
 75   76       Gibraltar       24     191       8
 76   77          Gambia        7      50       7
 77   78          Turkey        7      26       4
 78   79         Croatia        8      26       3
 79   80        Maldives        8      25       3
 80   81        Thailand        8       0       0
 81   82        Eswatini       18       0       0
 82   83      Seychelles        7       0       0
 83   84           Samoa        9       0       0
 84   85         Estonia        9       0       0
 85   86        Cameroon       11       0       0
 86   87          Greece        6       0       0,
     Pos                Team  Matches  Points  Rating
 0     1     Australia Women       21    3603     172
 1     2       England Women       28    3342     119
 2     3  South Africa Women       26    3098     119
 3     4         India Women       27    2820     104
 4     5   New Zealand Women       28    2688      96
 5     6   West Indies Women       29    2743      95
 6     7    Bangladesh Women       14     977      70
 7     8     Sri Lanka Women       12     820      68
 8     9      Thailand Women       13     883      68
 9    10      Pakistan Women       27    1678      62
 10   11       Ireland Women       16     605      38
 11   12   Netherlands Women       11      89       8
 12   13      Zimbabwe Women       11       0       0,
     Pos                Team  Matches  Points  Rating
 0     1     Australia Women       32    9548     298
 1     2       England Women       38   10841     285
 2     3   New Zealand Women       31    8247     266
 3     4         India Women       48   12736     265
 4     5  South Africa Women       27    6831     253
 5     6   West Indies Women       30    6872     229
 6     7      Pakistan Women       30    6592     220
 7     8     Sri Lanka Women       32    6875     215
 8     9    Bangladesh Women       31    5851     189
 9    10       Ireland Women       29    5132     177
 10   11           PNG Women       15    2396     160
 11   12      Zimbabwe Women       23    3658     159
 12   13      Thailand Women       31    4928     159
 13   14      Scotland Women       16    2253     141
 14   15           UAE Women       42    5125     122
 15   16   Netherlands Women       14    1619     116
 16   17       Namibia Women       28    3080     110
 17   18      Tanzania Women       23    2516     109
 18   19        Uganda Women       48    5063     105
 19   20     Indonesia Women       11    1148     104
 20   21         Nepal Women       24    2477     103
 21   22     Hong Kong Women       29    2536      87
 22   23         Kenya Women       37    2775      75
 23   24        Rwanda Women       37    2641      71
 24   25           USA Women       14     971      69
 25   26        Jersey Women       14     953      68
 26   27         Italy Women       17    1102      65
 27   28      Malaysia Women       34    2182      64
 28   29       Nigeria Women       32    1933      60
 29   30        Brazil Women       24    1192      50
 30   31       Germany Women       25    1237      49
 31   32        Canada Women        6     277      46
 32   33        France Women       19     861      45
 33   34        Belize Women        3     135      45
 34   35       Vanuatu Women       10     444      44
 35   36        Sweden Women       15     559      37
 36   37         Spain Women        8     256      32
 37   38  Sierra Leone Women       12     352      29
 38   39    Mozambique Women       12     328      27
 39   40      Botswana Women       23     532      23
 40   41        Bhutan Women        9     207      23
 41   42          Oman Women       13     289      22
 42   43     Singapore Women       21     444      21
 43   44         Samoa Women       10     205      21
 44   45        Malawi Women        4      71      18
 45   46        Kuwait Women       16     278      17
 46   47       Bahrain Women        8     138      17
 47   48       Romania Women        7     105      15
 48   49         Qatar Women       21     245      12
 49   50    Costa Rica Women        3      34      11
 50   51     Argentina Women       17      76       4
 51   52         Japan Women        8      28       4
 52   53          Fiji Women       10      28       3
 53   54      Cambodia Women       13      28       2
 54   55      Cameroon Women        7       4       1
 55   56      Eswatini Women        9       0       0
 56   57  Phlilippines Women       11       0       0
 57   58        Norway Women        9       0       0
 58   59         Ghana Women        9       0       0
 59   60       Austria Women       21       0       0
 60   61          Peru Women        5       0       0]

In [7]:
type(cricket)

list

In [8]:
cricket[0]

   Pos          Team  Matches  Points  Rating
0    1         India       26    3097     119
1    2     Australia       24    2850     119
2    3       England       36    4103     114
3    4  South Africa       21    2182     104
4    5   New Zealand       23    2291     100
5    6      Pakistan       22    1902      86
6    7     Sri Lanka       24    2015      84
7    8   West Indies       25    1906      76
8    9    Bangladesh       19     873      46
9   10      Zimbabwe        7     223      32

In [9]:
cricket[1]

    Pos          Team  Matches  Points  Rating
0     1     Australia       23    2714     118
1     2      Pakistan       20    2316     116
2     3         India       33    3807     115
3     4   New Zealand       27    2806     104
4     5       England       24    2426     101
5     6  South Africa       19    1910     101
6     7    Bangladesh       28    2661      95
7     8   Afghanistan       16    1404      88
8     9     Sri Lanka       32    2794      87
9    10   West Indies       35    2312      66
10   11      Zimbabwe       30    1641      55
11   12      Scotland       33    1662      50
12   13       Ireland       24    1052      44
13   14   Netherlands       28    1044      37
14   15         Nepal       40    1396      35
15   16       Namibia       28     813      29
16   17           USA       31     808      26
17   18          Oman       24     525      22
18   19           UAE       41     617      15
19   20           PNG       28     106       4

# ADD DATA

In [11]:
df=pd.DataFrame()
for i in range(len(cricket)):
    df=df.append(cricket[i])

C:\Users\Vishal\AppData\Local\Temp\ipykernel_8132\3116521926.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df=df.append(cricket[i])
C:\Users\Vishal\AppData\Local\Temp\ipykernel_8132\3116521926.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df=df.append(cricket[i])
C:\Users\Vishal\AppData\Local\Temp\ipykernel_8132\3116521926.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df=df.append(cricket[i])

In [12]:
df

    Pos                Team  Matches  Points  Rating
0     1               India       26    3097     119
1     2           Australia       24    2850     119
2     3             England       36    4103     114
3     4        South Africa       21    2182     104
4     5         New Zealand       23    2291     100
5     6            Pakistan       22    1902      86
6     7           Sri Lanka       24    2015      84
7     8         West Indies       25    1906      76
8     9          Bangladesh       19     873      46
9    10            Zimbabwe        7     223      32
0     1           Australia       23    2714     118
1     2            Pakistan       20    2316     116
2     3               India       33    3807     115
3     4         New Zealand       27    2806     104
4     5             England       24    2426     101
5     6        South Africa       19    1910     101
6     7          Bangladesh       28    2661      95
7     8         Afghanistan       16    1404      88
8     9           Sri Lanka       32    2794      87
9    10         West Indies       35    2312      66
10   11            Zimbabwe       30    1641      55
11   12            Scotland       33    1662      50
12   13             Ireland       24    1052      44
13   14         Netherlands       28    1044      37
14   15               Nepal       40    1396      35
15   16             Namibia       28     813      29
16   17                 USA       31     808      26
17   18                Oman       24     525      22
18   19                 UAE       41     617      15
19   20                 PNG       28     106       4
0     1               India       52   13889     267
1     2             England       39   10117     259
2     3         New Zealand       46   11794     256
3     4            Pakistan       50   12719     254
4     5        South Africa       32    8080     253
5     6           Australia       31    7681     248
6     7         West Indies       34    8086     238
7     8           Sri Lanka       37    8774     237
8     9          Bangladesh       39    8656     222
9    10         Afghanistan       27    5915     219
10   11            Zimbabwe       36    7087     197
11   12             Ireland       37    7168     194
12   13             Namibia       17    3228     190
13   14            Scotland       12    2195     183
14   15         Netherlands       19    3445     181
15   16                 UAE       17    3029     178
16   17               Nepal       14    2491     178
17   18           Hong Kong       14    2052     147
18   19              Canada       13    1871     144
19   20                Oman       13    1823     140
20   21              Jersey       13    1718     132
21   22                 PNG       12    1581     132
22   23                 USA        9    1183     131
23   24              Uganda       42    5407     129
24   25            Malaysia       27    3307     122
25   26               Qatar        7     832     119
26   27              Kuwait       14    1648     118
27   28             Bahrain       27    2848     105
28   29               Kenya       30    3137     105
29   30            Tanzania       31    3151     102
30   31             Germany       25    2424      97
31   32             Bermuda        9     862      96
32   33        Saudi Arabia        9     859      95
33   34               Spain       18    1649      92
34   35               Italy       12    1094      91
35   36           Singapore       23    1840      80
36   37      Cayman Islands        7     521      74
37   38            Portugal       16    1167      73
38   39             Denmark       17    1234      73
39   40             Belgium       18    1237      69
40   41             Nigeria       15    1026      68
41   42             Vanuatu        9     607      67
42   43            Guernsey       13     876      67
43   44         Isle of Man       15     949      63
44   45             Austria       24    1465      61
45   46              Norway       15     852      57
46   47            Botswana       24    1300      54
47   48             Finland       18     953      53
48   49              France       10     515      52
49   50             Romania       18     884      49
50   51              Malawi       14     682      49
51   52      Czech Republic       24    1101      46
52   53              Sweden       18     759      42
53   54        Cook Islands        6     245      41
54   55           Indonesia       10     372      37
55   56          Mozambique       21     759      36
56   57        Sierra Leone       12     421      35
57   58         Switzerland       11     376      34
58   59              Bhutan        7     239      34
59   60               Malta       33    1120      34
60   61               Japan        7     236      34
61   62               Ghana       16     516      32
62   63              Rwanda       38    1171      31
63   64         Philippines        5     154      31
64   65           Argentina        9     274      30
65   66                Fiji       10     304      30
66   67          Luxembourg       22     660      30
67   68              Cyprus        8     206      26
68   69             Bahamas       10     241      24
69   70              Panama        7     160      23
70   71              Belize        3      66      22
71   72              Serbia       17     351      21
72   73             Hungary       17     264      16
73   74            Bulgaria       30     289      10
74   75             Lesotho        9      82       9
75   76           Gibraltar       24     191       8
76   77              Gambia        7      50       7
77   78              Turkey        7      26       4
78   79             Croatia        8      26       3
79   80            Maldives        8      25       3
80   81            Thailand        8       0       0
81   82            Eswatini       18       0       0
82   83          Seychelles        7       0       0
83   84               Samoa        9       0       0
84   85             Estonia        9       0       0
85   86            Cameroon       11       0       0
86   87              Greece        6       0       0
0     1     Australia Women       21    3603     172
1     2       England Women       28    3342     119
2     3  South Africa Women       26    3098     119
3     4         India Women       27    2820     104
4     5   New Zealand Women       28    2688      96
5     6   West Indies Women       29    2743      95
6     7    Bangladesh Women       14     977      70
7     8     Sri Lanka Women       12     820      68
8     9      Thailand Women       13     883      68
9    10      Pakistan Women       27    1678      62
10   11       Ireland Women       16     605      38
11   12   Netherlands Women       11      89       8
12   13      Zimbabwe Women       11       0       0
0     1     Australia Women       32    9548     298
1     2       England Women       38   10841     285
2     3   New Zealand Women       31    8247     266
3     4         India Women       48   12736     265
4     5  South Africa Women       27    6831     253
5     6   West Indies Women       30    6872     229
6     7      Pakistan Women       30    6592     220
7     8     Sri Lanka Women       32    6875     215
8     9    Bangladesh Women       31    5851     189
9    10       Ireland Women       29    5132     177
10   11           PNG Women       15    2396     160
11   12      Zimbabwe Women       23    3658     159
12   13      Thailand Women       31    4928     159
13   14      Scotland Women       16    2253     141
14   15           UAE Women       42    5125     122
15   16   Netherlands Women       14    1619     116
16   17       Namibia Women       28    3080     110
17   18      Tanzania Women       23    2516     109
18   19        Uganda Women       48    5063     105
19   20     Indonesia Women       11    1148     104
20   21         Nepal Women       24    2477     103
21   22     Hong Kong Women       29    2536      87
22   23         Kenya Women       37    2775      75
23   24        Rwanda Women       37    2641      71
24   25           USA Women       14     971      69
25   26        Jersey Women       14     953      68
26   27         Italy Women       17    1102      65
27   28      Malaysia Women       34    2182      64
28   29       Nigeria Women       32    1933      60
29   30        Brazil Women       24    1192      50
30   31       Germany Women       25    1237      49
31   32        Canada Women        6     277      46
32   33        France Women       19     861      45
33   34        Belize Women        3     135      45
34   35       Vanuatu Women       10     444      44
35   36        Sweden Women       15     559      37
36   37         Spain Women        8     256      32
37   38  Sierra Leone Women       12     352      29
38   39    Mozambique Women       12     328      27
39   40      Botswana Women       23     532      23
40   41        Bhutan Women        9     207      23
41   42          Oman Women       13     289      22
42   43     Singapore Women       21     444      21
43   44         Samoa Women       10     205      21
44   45        Malawi Women        4      71      18
45   46        Kuwait Women       16     278      17
46   47       Bahrain Women        8     138      17
47   48       Romania Women        7     105      15
48   49         Qatar Women       21     245      12
49   50    Costa Rica Women        3      34      11
50   51     Argentina Women       17      76       4
51   52         Japan Women        8      28       4
52   53          Fiji Women       10      28       3
53   54      Cambodia Women       13      28       2
54   55      Cameroon Women        7       4       1
55   56      Eswatini Women        9       0       0
56   57  Phlilippines Women       11       0       0
57   58        Norway Women        9       0       0
58   59         Ghana Women        9       0       0
59   60       Austria Women       21       0       0
60   61          Peru Women        5       0       0

In [13]:
df.shape

(191, 5)

# INDEXING SERIALWISE

In [14]:
df.index=range(191)

In [15]:
df

     Pos                Team  Matches  Points  Rating
0      1               India       26    3097     119
1      2           Australia       24    2850     119
2      3             England       36    4103     114
3      4        South Africa       21    2182     104
4      5         New Zealand       23    2291     100
5      6            Pakistan       22    1902      86
6      7           Sri Lanka       24    2015      84
7      8         West Indies       25    1906      76
8      9          Bangladesh       19     873      46
9     10            Zimbabwe        7     223      32
10     1           Australia       23    2714     118
11     2            Pakistan       20    2316     116
12     3               India       33    3807     115
13     4         New Zealand       27    2806     104
14     5             England       24    2426     101
15     6        South Africa       19    1910     101
16     7          Bangladesh       28    2661      95
17     8         Afghanistan       16    1404      88
18     9           Sri Lanka       32    2794      87
19    10         West Indies       35    2312      66
20    11            Zimbabwe       30    1641      55
21    12            Scotland       33    1662      50
22    13             Ireland       24    1052      44
23    14         Netherlands       28    1044      37
24    15               Nepal       40    1396      35
25    16             Namibia       28     813      29
26    17                 USA       31     808      26
27    18                Oman       24     525      22
28    19                 UAE       41     617      15
29    20                 PNG       28     106       4
30     1               India       52   13889     267
31     2             England       39   10117     259
32     3         New Zealand       46   11794     256
33     4            Pakistan       50   12719     254
34     5        South Africa       32    8080     253
35     6           Australia       31    7681     248
36     7         West Indies       34    8086     238
37     8           Sri Lanka       37    8774     237
38     9          Bangladesh       39    8656     222
39    10         Afghanistan       27    5915     219
40    11            Zimbabwe       36    7087     197
41    12             Ireland       37    7168     194
42    13             Namibia       17    3228     190
43    14            Scotland       12    2195     183
44    15         Netherlands       19    3445     181
45    16                 UAE       17    3029     178
46    17               Nepal       14    2491     178
47    18           Hong Kong       14    2052     147
48    19              Canada       13    1871     144
49    20                Oman       13    1823     140
50    21              Jersey       13    1718     132
51    22                 PNG       12    1581     132
52    23                 USA        9    1183     131
53    24              Uganda       42    5407     129
54    25            Malaysia       27    3307     122
55    26               Qatar        7     832     119
56    27              Kuwait       14    1648     118
57    28             Bahrain       27    2848     105
58    29               Kenya       30    3137     105
59    30            Tanzania       31    3151     102
60    31             Germany       25    2424      97
61    32             Bermuda        9     862      96
62    33        Saudi Arabia        9     859      95
63    34               Spain       18    1649      92
64    35               Italy       12    1094      91
65    36           Singapore       23    1840      80
66    37      Cayman Islands        7     521      74
67    38            Portugal       16    1167      73
68    39             Denmark       17    1234      73
69    40             Belgium       18    1237      69
70    41             Nigeria       15    1026      68
71    42             Vanuatu        9     607      67
72    43            Guernsey       13     876      67
73    44         Isle of Man       15     949      63
74    45             Austria       24    1465      61
75    46              Norway       15     852      57
76    47            Botswana       24    1300      54
77    48             Finland       18     953      53
78    49              France       10     515      52
79    50             Romania       18     884      49
80    51              Malawi       14     682      49
81    52      Czech Republic       24    1101      46
82    53              Sweden       18     759      42
83    54        Cook Islands        6     245      41
84    55           Indonesia       10     372      37
85    56          Mozambique       21     759      36
86    57        Sierra Leone       12     421      35
87    58         Switzerland       11     376      34
88    59              Bhutan        7     239      34
89    60               Malta       33    1120      34
90    61               Japan        7     236      34
91    62               Ghana       16     516      32
92    63              Rwanda       38    1171      31
93    64         Philippines        5     154      31
94    65           Argentina        9     274      30
95    66                Fiji       10     304      30
96    67          Luxembourg       22     660      30
97    68              Cyprus        8     206      26
98    69             Bahamas       10     241      24
99    70              Panama        7     160      23
100   71              Belize        3      66      22
101   72              Serbia       17     351      21
102   73             Hungary       17     264      16
103   74            Bulgaria       30     289      10
104   75             Lesotho        9      82       9
105   76           Gibraltar       24     191       8
106   77              Gambia        7      50       7
107   78              Turkey        7      26       4
108   79             Croatia        8      26       3
109   80            Maldives        8      25       3
110   81            Thailand        8       0       0
111   82            Eswatini       18       0       0
112   83          Seychelles        7       0       0
113   84               Samoa        9       0       0
114   85             Estonia        9       0       0
115   86            Cameroon       11       0       0
116   87              Greece        6       0       0
117    1     Australia Women       21    3603     172
118    2       England Women       28    3342     119
119    3  South Africa Women       26    3098     119
120    4         India Women       27    2820     104
121    5   New Zealand Women       28    2688      96
122    6   West Indies Women       29    2743      95
123    7    Bangladesh Women       14     977      70
124    8     Sri Lanka Women       12     820      68
125    9      Thailand Women       13     883      68
126   10      Pakistan Women       27    1678      62
127   11       Ireland Women       16     605      38
128   12   Netherlands Women       11      89       8
129   13      Zimbabwe Women       11       0       0
130    1     Australia Women       32    9548     298
131    2       England Women       38   10841     285
132    3   New Zealand Women       31    8247     266
133    4         India Women       48   12736     265
134    5  South Africa Women       27    6831     253
135    6   West Indies Women       30    6872     229
136    7      Pakistan Women       30    6592     220
137    8     Sri Lanka Women       32    6875     215
138    9    Bangladesh Women       31    5851     189
139   10       Ireland Women       29    5132     177
140   11           PNG Women       15    2396     160
141   12      Zimbabwe Women       23    3658     159
142   13      Thailand Women       31    4928     159
143   14      Scotland Women       16    2253     141
144   15           UAE Women       42    5125     122
145   16   Netherlands Women       14    1619     116
146   17       Namibia Women       28    3080     110
147   18      Tanzania Women       23    2516     109
148   19        Uganda Women       48    5063     105
149   20     Indonesia Women       11    1148     104
150   21         Nepal Women       24    2477     103
151   22     Hong Kong Women       29    2536      87
152   23         Kenya Women       37    2775      75
153   24        Rwanda Women       37    2641      71
154   25           USA Women       14     971      69
155   26        Jersey Women       14     953      68
156   27         Italy Women       17    1102      65
157   28      Malaysia Women       34    2182      64
158   29       Nigeria Women       32    1933      60
159   30        Brazil Women       24    1192      50
160   31       Germany Women       25    1237      49
161   32        Canada Women        6     277      46
162   33        France Women       19     861      45
163   34        Belize Women        3     135      45
164   35       Vanuatu Women       10     444      44
165   36        Sweden Women       15     559      37
166   37         Spain Women        8     256      32
167   38  Sierra Leone Women       12     352      29
168   39    Mozambique Women       12     328      27
169   40      Botswana Women       23     532      23
170   41        Bhutan Women        9     207      23
171   42          Oman Women       13     289      22
172   43     Singapore Women       21     444      21
173   44         Samoa Women       10     205      21
174   45        Malawi Women        4      71      18
175   46        Kuwait Women       16     278      17
176   47       Bahrain Women        8     138      17
177   48       Romania Women        7     105      15
178   49         Qatar Women       21     245      12
179   50    Costa Rica Women        3      34      11
180   51     Argentina Women       17      76       4
181   52         Japan Women        8      28       4
182   53          Fiji Women       10      28       3
183   54      Cambodia Women       13      28       2
184   55      Cameroon Women        7       4       1
185   56      Eswatini Women        9       0       0
186   57  Phlilippines Women       11       0       0
187   58        Norway Women        9       0       0
188   59         Ghana Women        9       0       0
189   60       Austria Women       21       0       0
190   61          Peru Women        5       0       0

# POSITION SERIAL WISE

In [16]:
df.Pos=range(191)

In [17]:
df

     Pos                Team  Matches  Points  Rating
0      0               India       26    3097     119
1      1           Australia       24    2850     119
2      2             England       36    4103     114
3      3        South Africa       21    2182     104
4      4         New Zealand       23    2291     100
5      5            Pakistan       22    1902      86
6      6           Sri Lanka       24    2015      84
7      7         West Indies       25    1906      76
8      8          Bangladesh       19     873      46
9      9            Zimbabwe        7     223      32
10    10           Australia       23    2714     118
11    11            Pakistan       20    2316     116
12    12               India       33    3807     115
13    13         New Zealand       27    2806     104
14    14             England       24    2426     101
15    15        South Africa       19    1910     101
16    16          Bangladesh       28    2661      95
17    17         Afghanistan       16    1404      88
18    18           Sri Lanka       32    2794      87
19    19         West Indies       35    2312      66
20    20            Zimbabwe       30    1641      55
21    21            Scotland       33    1662      50
22    22             Ireland       24    1052      44
23    23         Netherlands       28    1044      37
24    24               Nepal       40    1396      35
25    25             Namibia       28     813      29
26    26                 USA       31     808      26
27    27                Oman       24     525      22
28    28                 UAE       41     617      15
29    29                 PNG       28     106       4
30    30               India       52   13889     267
31    31             England       39   10117     259
32    32         New Zealand       46   11794     256
33    33            Pakistan       50   12719     254
34    34        South Africa       32    8080     253
35    35           Australia       31    7681     248
36    36         West Indies       34    8086     238
37    37           Sri Lanka       37    8774     237
38    38          Bangladesh       39    8656     222
39    39         Afghanistan       27    5915     219
40    40            Zimbabwe       36    7087     197
41    41             Ireland       37    7168     194
42    42             Namibia       17    3228     190
43    43            Scotland       12    2195     183
44    44         Netherlands       19    3445     181
45    45                 UAE       17    3029     178
46    46               Nepal       14    2491     178
47    47           Hong Kong       14    2052     147
48    48              Canada       13    1871     144
49    49                Oman       13    1823     140
50    50              Jersey       13    1718     132
51    51                 PNG       12    1581     132
52    52                 USA        9    1183     131
53    53              Uganda       42    5407     129
54    54            Malaysia       27    3307     122
55    55               Qatar        7     832     119
56    56              Kuwait       14    1648     118
57    57             Bahrain       27    2848     105
58    58               Kenya       30    3137     105
59    59            Tanzania       31    3151     102
60    60             Germany       25    2424      97
61    61             Bermuda        9     862      96
62    62        Saudi Arabia        9     859      95
63    63               Spain       18    1649      92
64    64               Italy       12    1094      91
65    65           Singapore       23    1840      80
66    66      Cayman Islands        7     521      74
67    67            Portugal       16    1167      73
68    68             Denmark       17    1234      73
69    69             Belgium       18    1237      69
70    70             Nigeria       15    1026      68
71    71             Vanuatu        9     607      67
72    72            Guernsey       13     876      67
73    73         Isle of Man       15     949      63
74    74             Austria       24    1465      61
75    75              Norway       15     852      57
76    76            Botswana       24    1300      54
77    77             Finland       18     953      53
78    78              France       10     515      52
79    79             Romania       18     884      49
80    80              Malawi       14     682      49
81    81      Czech Republic       24    1101      46
82    82              Sweden       18     759      42
83    83        Cook Islands        6     245      41
84    84           Indonesia       10     372      37
85    85          Mozambique       21     759      36
86    86        Sierra Leone       12     421      35
87    87         Switzerland       11     376      34
88    88              Bhutan        7     239      34
89    89               Malta       33    1120      34
90    90               Japan        7     236      34
91    91               Ghana       16     516      32
92    92              Rwanda       38    1171      31
93    93         Philippines        5     154      31
94    94           Argentina        9     274      30
95    95                Fiji       10     304      30
96    96          Luxembourg       22     660      30
97    97              Cyprus        8     206      26
98    98             Bahamas       10     241      24
99    99              Panama        7     160      23
100  100              Belize        3      66      22
101  101              Serbia       17     351      21
102  102             Hungary       17     264      16
103  103            Bulgaria       30     289      10
104  104             Lesotho        9      82       9
105  105           Gibraltar       24     191       8
106  106              Gambia        7      50       7
107  107              Turkey        7      26       4
108  108             Croatia        8      26       3
109  109            Maldives        8      25       3
110  110            Thailand        8       0       0
111  111            Eswatini       18       0       0
112  112          Seychelles        7       0       0
113  113               Samoa        9       0       0
114  114             Estonia        9       0       0
115  115            Cameroon       11       0       0
116  116              Greece        6       0       0
117  117     Australia Women       21    3603     172
118  118       England Women       28    3342     119
119  119  South Africa Women       26    3098     119
120  120         India Women       27    2820     104
121  121   New Zealand Women       28    2688      96
122  122   West Indies Women       29    2743      95
123  123    Bangladesh Women       14     977      70
124  124     Sri Lanka Women       12     820      68
125  125      Thailand Women       13     883      68
126  126      Pakistan Women       27    1678      62
127  127       Ireland Women       16     605      38
128  128   Netherlands Women       11      89       8
129  129      Zimbabwe Women       11       0       0
130  130     Australia Women       32    9548     298
131  131       England Women       38   10841     285
132  132   New Zealand Women       31    8247     266
133  133         India Women       48   12736     265
134  134  South Africa Women       27    6831     253
135  135   West Indies Women       30    6872     229
136  136      Pakistan Women       30    6592     220
137  137     Sri Lanka Women       32    6875     215
138  138    Bangladesh Women       31    5851     189
139  139       Ireland Women       29    5132     177
140  140           PNG Women       15    2396     160
141  141      Zimbabwe Women       23    3658     159
142  142      Thailand Women       31    4928     159
143  143      Scotland Women       16    2253     141
144  144           UAE Women       42    5125     122
145  145   Netherlands Women       14    1619     116
146  146       Namibia Women       28    3080     110
147  147      Tanzania Women       23    2516     109
148  148        Uganda Women       48    5063     105
149  149     Indonesia Women       11    1148     104
150  150         Nepal Women       24    2477     103
151  151     Hong Kong Women       29    2536      87
152  152         Kenya Women       37    2775      75
153  153        Rwanda Women       37    2641      71
154  154           USA Women       14     971      69
155  155        Jersey Women       14     953      68
156  156         Italy Women       17    1102      65
157  157      Malaysia Women       34    2182      64
158  158       Nigeria Women       32    1933      60
159  159        Brazil Women       24    1192      50
160  160       Germany Women       25    1237      49
161  161        Canada Women        6     277      46
162  162        France Women       19     861      45
163  163        Belize Women        3     135      45
164  164       Vanuatu Women       10     444      44
165  165        Sweden Women       15     559      37
166  166         Spain Women        8     256      32
167  167  Sierra Leone Women       12     352      29
168  168    Mozambique Women       12     328      27
169  169      Botswana Women       23     532      23
170  170        Bhutan Women        9     207      23
171  171          Oman Women       13     289      22
172  172     Singapore Women       21     444      21
173  173         Samoa Women       10     205      21
174  174        Malawi Women        4      71      18
175  175        Kuwait Women       16     278      17
176  176       Bahrain Women        8     138      17
177  177       Romania Women        7     105      15
178  178         Qatar Women       21     245      12
179  179    Costa Rica Women        3      34      11
180  180     Argentina Women       17      76       4
181  181         Japan Women        8      28       4
182  182          Fiji Women       10      28       3
183  183      Cambodia Women       13      28       2
184  184      Cameroon Women        7       4       1
185  185      Eswatini Women        9       0       0
186  186  Phlilippines Women       11       0       0
187  187        Norway Women        9       0       0
188  188         Ghana Women        9       0       0
189  189       Austria Women       21       0       0
190  190          Peru Women        5       0       0

# CHANGING POSITION INTO INDEXING (SET.INDEX)

In [18]:
df=df.set_index('Pos')

In [19]:
df

                   Team  Matches  Points  Rating
Pos
0                 India       26    3097     119
1             Australia       24    2850     119
2               England       36    4103     114
3          South Africa       21    2182     104
4           New Zealand       23    2291     100
5              Pakistan       22    1902      86
6             Sri Lanka       24    2015      84
7           West Indies       25    1906      76
8            Bangladesh       19     873      46
9              Zimbabwe        7     223      32
10            Australia       23    2714     118
11             Pakistan       20    2316     116
12                India       33    3807     115
13          New Zealand       27    2806     104
14              England       24    2426     101
15         South Africa       19    1910     101
16           Bangladesh       28    2661      95
17          Afghanistan       16    1404      88
18            Sri Lanka       32    2794      87
19          West Indies       35    2312      66
20             Zimbabwe       30    1641      55
21             Scotland       33    1662      50
22              Ireland       24    1052      44
23          Netherlands       28    1044      37
24                Nepal       40    1396      35
25              Namibia       28     813      29
26                  USA       31     808      26
27                 Oman       24     525      22
28                  UAE       41     617      15
29                  PNG       28     106       4
30                India       52   13889     267
31              England       39   10117     259
32          New Zealand       46   11794     256
33             Pakistan       50   12719     254
34         South Africa       32    8080     253
35            Australia       31    7681     248
36          West Indies       34    8086     238
37            Sri Lanka       37    8774     237
38           Bangladesh       39    8656     222
39          Afghanistan       27    5915     219
40             Zimbabwe       36    7087     197
41              Ireland       37    7168     194
42              Namibia       17    3228     190
43             Scotland       12    2195     183
44          Netherlands       19    3445     181
45                  UAE       17    3029     178
46                Nepal       14    2491     178
47            Hong Kong       14    2052     147
48               Canada       13    1871     144
49                 Oman       13    1823     140
50               Jersey       13    1718     132
51                  PNG       12    1581     132
52                  USA        9    1183     131
53               Uganda       42    5407     129
54             Malaysia       27    3307     122
55                Qatar        7     832     119
56               Kuwait       14    1648     118
57              Bahrain       27    2848     105
58                Kenya       30    3137     105
59             Tanzania       31    3151     102
60              Germany       25    2424      97
61              Bermuda        9     862      96
62         Saudi Arabia        9     859      95
63                Spain       18    1649      92
64                Italy       12    1094      91
65            Singapore       23    1840      80
66       Cayman Islands        7     521      74
67             Portugal       16    1167      73
68              Denmark       17    1234      73
69              Belgium       18    1237      69
70              Nigeria       15    1026      68
71              Vanuatu        9     607      67
72             Guernsey       13     876      67
73          Isle of Man       15     949      63
74              Austria       24    1465      61
75               Norway       15     852      57
76             Botswana       24    1300      54
77              Finland       18     953      53
78               France       10     515      52
79              Romania       18     884      49
80               Malawi       14     682      49
81       Czech Republic       24    1101      46
82               Sweden       18     759      42
83         Cook Islands        6     245      41
84            Indonesia       10     372      37
85           Mozambique       21     759      36
86         Sierra Leone       12     421      35
87          Switzerland       11     376      34
88               Bhutan        7     239      34
89                Malta       33    1120      34
90                Japan        7     236      34
91                Ghana       16     516      32
92               Rwanda       38    1171      31
93          Philippines        5     154      31
94            Argentina        9     274      30
95                 Fiji       10     304      30
96           Luxembourg       22     660      30
97               Cyprus        8     206      26
98              Bahamas       10     241      24
99               Panama        7     160      23
100              Belize        3      66      22
101              Serbia       17     351      21
102             Hungary       17     264      16
103            Bulgaria       30     289      10
104             Lesotho        9      82       9
105           Gibraltar       24     191       8
106              Gambia        7      50       7
107              Turkey        7      26       4
108             Croatia        8      26       3
109            Maldives        8      25       3
110            Thailand        8       0       0
111            Eswatini       18       0       0
112          Seychelles        7       0       0
113               Samoa        9       0       0
114             Estonia        9       0       0
115            Cameroon       11       0       0
116              Greece        6       0       0
117     Australia Women       21    3603     172
118       England Women       28    3342     119
119  South Africa Women       26    3098     119
120         India Women       27    2820     104
121   New Zealand Women       28    2688      96
122   West Indies Women       29    2743      95
123    Bangladesh Women       14     977      70
124     Sri Lanka Women       12     820      68
125      Thailand Women       13     883      68
126      Pakistan Women       27    1678      62
127       Ireland Women       16     605      38
128   Netherlands Women       11      89       8
129      Zimbabwe Women       11       0       0
130     Australia Women       32    9548     298
131       England Women       38   10841     285
132   New Zealand Women       31    8247     266
133         India Women       48   12736     265
134  South Africa Women       27    6831     253
135   West Indies Women       30    6872     229
136      Pakistan Women       30    6592     220
137     Sri Lanka Women       32    6875     215
138    Bangladesh Women       31    5851     189
139       Ireland Women       29    5132     177
140           PNG Women       15    2396     160
141      Zimbabwe Women       23    3658     159
142      Thailand Women       31    4928     159
143      Scotland Women       16    2253     141
144           UAE Women       42    5125     122
145   Netherlands Women       14    1619     116
146       Namibia Women       28    3080     110
147      Tanzania Women       23    2516     109
148        Uganda Women       48    5063     105
149     Indonesia Women       11    1148     104
150         Nepal Women       24    2477     103
151     Hong Kong Women       29    2536      87
152         Kenya Women       37    2775      75
153        Rwanda Women       37    2641      71
154           USA Women       14     971      69
155        Jersey Women       14     953      68
156         Italy Women       17    1102      65
157      Malaysia Women       34    2182      64
158       Nigeria Women       32    1933      60
159        Brazil Women       24    1192      50
160       Germany Women       25    1237      49
161        Canada Women        6     277      46
162        France Women       19     861      45
163        Belize Women        3     135      45
164       Vanuatu Women       10     444      44
165        Sweden Women       15     559      37
166         Spain Women        8     256      32
167  Sierra Leone Women       12     352      29
168    Mozambique Women       12     328      27
169      Botswana Women       23     532      23
170        Bhutan Women        9     207      23
171          Oman Women       13     289      22
172     Singapore Women       21     444      21
173         Samoa Women       10     205      21
174        Malawi Women        4      71      18
175        Kuwait Women       16     278      17
176       Bahrain Women        8     138      17
177       Romania Women        7     105      15
178         Qatar Women       21     245      12
179    Costa Rica Women        3      34      11
180     Argentina Women       17      76       4
181         Japan Women        8      28       4
182          Fiji Women       10      28       3
183      Cambodia Women       13      28       2
184      Cameroon Women        7       4       1
185      Eswatini Women        9       0       0
186  Phlilippines Women       11       0       0
187        Norway Women        9       0       0
188         Ghana Women        9       0       0
189       Austria Women       21       0       0
190          Peru Women        5       0       0

In [20]:
df.to_csv('htmlcricket.csv')

In [21]:
import matplotlib as plt

In [22]:
df.head()

             Team  Matches  Points  Rating
Pos
0           India       26    3097     119
1       Australia       24    2850     119
2         England       36    4103     114
3    South Africa       21    2182     104
4     New Zealand       23    2291     100